This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support).
Scanning style file ./0_bachelorarbeit.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file 0_bachelorarbeit.acn....done (17 entries accepted, 0 rejected).
Sorting entries....done (69 comparisons).
Generating output file 0_bachelorarbeit.acr....done (22 lines written, 0 warnings).
Output written in 0_bachelorarbeit.acr.
Transcript written in 0_bachelorarbeit.alg.
