This is makeindex, version 2.15 [TeX Live 2022/dev] (kpathsea + Thai support).
Scanning style file ./0_bachelorarbeit.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file 0_bachelorarbeit.acn....done (129 entries accepted, 0 rejected).
Sorting entries....done (1037 comparisons).
Generating output file 0_bachelorarbeit.acr....done (93 lines written, 0 warnings).
Output written in 0_bachelorarbeit.acr.
Transcript written in 0_bachelorarbeit.alg.
