version: "3.7"

services:
  latex:
    image: blang/latex
    volumes:
      #- C:\Users\bruno\Dropbox\Estudos_Avancados\Angewandte_Informatik\Praxissemester_Bachelorarbeit\:/home/bachelorarbeit/
      - ${PWD}:/home/bachelorarbeit/
    working_dir: /home/bachelorarbeit
    environment:
      - TZ=
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    entrypoint: zsh -c "while sleep 1000; do :; done"