This is makeindex, version 2.15 [TeX Live 2022/dev] (kpathsea + Thai support).
Scanning style file ./0_praxis_main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file 0_praxis_main.acn....done (30 entries accepted, 0 rejected).
Sorting entries....done (179 comparisons).
Generating output file 0_praxis_main.acr....done (46 lines written, 0 warnings).
Output written in 0_praxis_main.acr.
Transcript written in 0_praxis_main.alg.
