version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.8.2
    volumes:
      -  ${PWD}/loki-config.yaml:/etc/loki/local-config.yaml
     # -  ${PWD}/archive/loki-config-basic.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml 
    networks:
      - loki

  Opfersystem1:
    image: grafana/promtail:2.8.2
    container_name: Opfersystem1
    volumes:
      - ${PWD}/promtail-local-config_opfer1.yaml:/etc/promtail/promtail-config.yaml
      - ${PWD}/temp2/:/opt/
    command: -config.file=/etc/promtail/promtail-config.yaml 
             -config.expand-env=true 
    networks:
      - loki

  # Opfersystem2:
  #   image: grafana/promtail:2.8.2
  #   container_name: Opfersystem2
  #   volumes:
  #     - ${PWD}/promtail-local-config_opfer2.yaml:/etc/promtail/promtail-config.yaml
  #     - ${PWD}/temp/auth.log.3.gz:/opt/auth.log.3.gz
  #     - ${PWD}/temp/auth.log.4.gz:/opt/auth.log.4.gz
  #   command: -config.file=/etc/promtail/promtail-config.yaml 
  #            -config.expand-env=true 
  #            #-querier.max-outstanding-requests-per-tenant= 2048
  #   networks:
  #     - loki

  # Opfersystem3:
  #   image: grafana/promtail:2.8.2
  #   container_name: Opfersystem3
  #   volumes:
  #     - ${PWD}/promtail-local-config_opfer3.yaml:/etc/promtail/promtail-config.yaml
  #     - ${PWD}/temp/auth.log.gz:/opt/auth.log.gz
  #   command: -config.file=/etc/promtail/promtail-config.yaml 
  #            -config.expand-env=true 
  #            #-querier.max-outstanding-requests-per-tenant= 2048
  #   networks:
  #     - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
