version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.4.1
    volumes:
      -  ${PWD}/loki-config.yaml:/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.8.2
    container_name: Opfersystem1
    volumes:
      - ${PWD}/promtail-local-config_opfer1.yaml:/etc/promtail/promtail-config.yaml
      #- ${PWD}/ssh.log:/opt/ssh.log
      #- ${PWD}/ssh1.log:/opt/ssh1.log
      #- ${PWD}/ssh2.log:/opt/ssh2.log
      - ${PWD}/temp/:/opt/
    command: -config.file=/etc/promtail/promtail-config.yaml 
             -config.expand-env=true 
             #-querier.max-outstanding-requests-per-tenant= 2048
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
