version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.3.0
    volumes:
      - /home/bruno/git/Praxisbericht_Bacherloarbeit/Bachelorarbeit/grafana/promtail-local-config_opfer1.yaml:/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.3.0
    container_name: Opfersystem1
    volumes:
      - ${PWD}/promtail-local-config_opfer1.yaml:/etc/promtail/promtail-config.yaml
      #- ${PWD}/ssh1.log:/opt/ssh.log
      - ${PWD}/temp/:/opt/
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - loki


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
