---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: tenant1

scrape_configs:
- job_name: sshlogs
  decompression:
    enabled: true
    initial_sleep: 10s
    format: gz
  static_configs:
  - targets:
      - loki
    labels:
      job: sshlogs
      #env: voidquart
      instance: Opfersystem1
      __path__: /opt/*

# scrape_configs:
# - job_name: sshlogs
#   static_configs:
#   - targets:
#       - loki
#     labels:
#       instance: Opfersystem1
#       env: voidquark
#       job: sshlogs
#       __path__: /opt/*.log
# - job_name: aptlogs
#   static_configs:
#   - targets:
#       - loki
#     labels:
#       instance: Opfersystem1
#       #env: voidquark
#       job: aptlogs
#       __path__: /var/log/apt/*.log
# - job_name: dpkg
#   static_configs:
#   - targets:
#       - loki
#     labels:
#       instance: Opfersystem1
#       #env: voidquark
#       job: dpkg
#       __path__: /var/log/apt/dpkg.log
# - job_name: webserver
#   static_configs:
#   - targets:
#       - loki
#     labels:
#       instance: Opfersystem1
#       #env: voidquark
#       job: webserver
#       __path__: /var/log/apache/*.log
