---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: tenant1

scrape_configs:
- job_name: sshlogs
  pipeline_stages:
  - match:
      selector: '{job="sshlogs"}'
      action: keep
      stages:
      - regex:
          expression:  '^(?P<time>[A-Za-z]{3}\s{1,2}\d{1,2}\s\d{2}:
                      \d{2}:\d{2})*'
      - timestamp:
          source: time
          format: RFC822Z #"Jan _2 15:04:05"
          location: "Europe/Berlin"
  decompression:
    enabled: true
    initial_delay: 15s
    format: gz
  static_configs:
  - targets:
      - loki
    labels:
      job: sshlogs
      #env: voidquart
      instance: Opfersystem1
      __path__: /opt/*.gz


#Apr 14 13:55:23 

 