---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: tenant1

scrape_configs:
- job_name: Processing SSH Logs
  static_configs:
  - targets:
      - loki
    labels:
      instance: Opfersystem_1
      env: voidquark
      job: SSH_LOGS
      __path__: /opt/*.log
