server:
  http_listen_port: 9080

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    pipeline_stages:
      - regex:
          expression: '^(.*)\.log(\.gz|\.zip)$'
          source: filepath
          action: drop
      - docker: {}
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log /var/log/**/*.log
          __compress__: gzip,zip