---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: tenant1

scrape_configs:
- job_name: sshlogs
  pipeline_stages:
  - match:
      selector: '{name="sshlogs"} |= "sshd["'
      stages:
      - regex:
          expression: '|= <_> user (?P<username>\w+) <_> port'
          #expression: '.*user=(?P<username>[^,]+),.*'
      - output:
          source: output
  decompression:
    enabled: true
    initial_delay: 15s
    format: gz
  static_configs:
  - targets:
      - loki
    labels:
      job: sshlogs
      #env: voidquart
      instance: Opfersystem1
      __path__: /opt/*.gz
      #__path__: /opt/*.log



  # pipeline_stages:
  #   - match:
  #     selector: '{job="sshlogs"}'
  #     stages:
  # - match:
  #     selector: '{job="server01_varlogs"} !~ "pam_unix"'
  #     action: drop
  #     drop_counter_reason: promtail_non_error
  # - output:
  #     source: msg
  # - match:
  #     selector: '{job="server01_varlogs"} |~ ".*Failed password for invalid user.*"'
  #     action: drop
  #     drop_counter_reason: promtail_noisy_error
  # - output:
  #     source: msg
    

