---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: tenant1

scrape_configs:
- job_name: sshlogs
  pipeline_stages:
  - match:
      selector: '{job="sshlogs"}'
      action: keep
      stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})'
      - timestamp:
          source: timestamp
          format: 2006-01-02 15:04:05,999
          location: "Europe/Berlin"
  decompression:
    enabled: true
    initial_delay: 15s
    format: gz
  static_configs:
  - targets:
      - loki
    labels:
      job: sshlogs
      #env: voidquart
      instance: Opfersystem3
      __path__: /opt/*.gz
